# Generated by Django 5.1.6 on 2025-03-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='accomplished',
            field=models.BooleanField(default=False),
        ),
    ]
